TatilSeyahatSitesi/Models/Siniflar/AnaSayfa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TatilSeyahatSitesi.Models.Siniflar
{
    public class AnaSayfa
    {
        //Bu tanımlamanın kolay yolu prop+tab+tab


        [Key]  //Birincil Anahtarı Belirtmek için Kullanıyoruz.
        public int ID { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
    }
}

TatilSeyahatSitesi/Controllers/AnasayfaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using TatilSeyahatSitesi.Models.Siniflar;

namespace TatilSeyahatSitesi.Controllers
{
    public class AnasayfaController : Controller
    {
        // GET: Anasayfa
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Blogs.Take(4).ToList();
            return View(degerler);
        }

        public PartialViewResult Partial1()  //Sol ve Orta Resimler için kullanıldı.
        {
            var degerler = c.Blogs.OrderByDescending(x => x.ID).Take(2).ToList();
            return PartialView(degerler);
        }

        public PartialViewResult Partial2()  //Sağ Resim için kullanıldı.
        {
            var degerler = c.Blogs.Where(x => x.ID==1).ToList();
            return PartialView(degerler);
        }

        public PartialViewResult Partial3()  //En Popüler Liste sıralaması için kullanıldı.
        {
            var degerler = c.Blogs.ToList();
            return PartialView(degerler);
        }
        public PartialViewResult Partial4()  //En Beğendiğimiz kısmın sol tarafı için kullanıldı.
        {
            var degerler = c.Blogs.Take(3).ToList();
            return PartialView(degerler);
        }
        public PartialViewResult Partial5()  //En Beğendiğimiz kısmın sağ tarafı için kullanıldı.
        {
            var degerler = c.Blogs.Take(3).OrderByDescending(x => x.ID).ToList();
            return PartialView(degerler);
        }
    }
}

TatilSeyahatSitesi/Views/Anasayfa/Index.cshtml
@using TatilSeyahatSitesi.Models.Siniflar
@model List<Blog>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<!DOCTYPE HTML>
<html>
<body>
    <div class="header-banner">
        <div class="wrap">
            <div class="banner">
                <div class="indent">
                    <h2 class="indent-left margin-bot">Tatil & Seyahat Bloğum</h2>
                    <div class="banner-left">
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/glass.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Restaurantlar</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/flight.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Uçuşlar</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/group.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Yapılacak Şeyler</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/key.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Araba Kiralama</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="header_bottom_right_images">

                        <div class="slider" style="width:650px; height:370px;">
                            <ul class="rslides" id="slider1">
                                @foreach (var x in Model)
                                {
                                    <li><img src="@x.BlogImage" alt=""></li>
                                }
                            </ul>

                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>

    <div class"content">
        <div class="wrap">
            <div class="wrapper">
                <div class="con-top">
                    <h3>Tatil Seyahat Bloğuma Hoşgeldiniz!</h3>
                    <p>
                        Seyahat etmeyi seviyorsanız, bilgi alabileceğiniz kaynakları çoktan keşfetmişsinizdir. Ancak henüz yeterli deneyiminiz yoksa ve yurtdışına seyahate çıkmayı düşünüyorsanız muhtemelen kafanız ne yapacağınız konusunda karışık olabilir. Nasıl seyahat edilir, ekonomik gezebilir miyim, rotamı nasıl belirlemeliyim, nasıl ucuza konaklarım, paramı nasıl taşırım, vize bilgilerini nereden bulabilirim… gibi sorular aklınızı kurcalıyorsa doğru yerdesiniz.

                        Deneyimli gezginlere bir sırt çantası, bir pasaport yeterli, ancak kısıtlı zamanı olanların gidecekleri yer hakkında araştırma ve planlama yapmasını tavsiye ediyorum. Aklında uçuşan binlerce soruya cevap verecek tüm kaynakları bir araya topladım.
                    </p>
                </div>
                @Html.Action("Partial1","Anasayfa")

                <div class="grids">
                    <div class="box1">

                        @Html.Action("Partial3", "Anasayfa")

                        @Html.Action("Partial4", "Anasayfa")

                        <div class="clear"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

TatilSeyahatSitesi/Views/Anasayfa/Partial1.cshtml
@using TatilSeyahatSitesi.Models.Siniflar
@model List<Blog>


<div class="con-bot">
    @foreach (var x in Model)
    {
        <div class="left">
            <div class="bot-left">
                <img src="@x.BlogImage" style="width:300px; height:150px;" alt="" />
            </div>
            <div class="left-text">
                <h4>@x.Baslik</h4>
                <span class="doller">@x.Tarih@*.ToString("dd.MM.yyyy")*@</span>
                <p>@x.Aciklama.Substring(0,85)...</p>
                <p><a href="/Blog/BlogDetay/@x.ID"><span class="read">Devamını Oku >></span></a></p>
            </div>
        </div>

    }

    @Html.Action("Partial2", "Anasayfa")
    <div class="clear"></div>

</div>

TatilSeyahatSitesi/Views/Anasayfa/Partial2.cshtml
@using TatilSeyahatSitesi.Models.Siniflar
@model List<Blog>


<div class="right">

    @foreach (var x in Model)
    {
        <div class="bot-left">
            <img src="@x.BlogImage" style="width:300px; height:150px" alt="" />
        </div>
        <div class="left-text">

            <h4>@x.Baslik</h4>
            <span class="doller">@x.Tarih@*.ToString("dd.MM.yyyy")*@</span>
            <p>@x.Aciklama.Substring(0, 87)...</p>
            <p><a href="/Blog/BlogDetay/@x.ID"><span class="read">Devamını Oku >></span></a></p>
        </div>

    }
</div>
<div class="clear"></div>

TatilSeyahatSitesi/Views/Anasayfa/Partial3.cshtml
@using TatilSeyahatSitesi.Models.Siniflar
@model List<Blog>

<div class="padding">
    <h4>En Popüler 10 Blog</h4>
    <ul class="list list-pad">

        @{ int i = 0;}
        @foreach (var x in Model)

        {
            <li class="list-bg"><span>@{ i++;} @i.</span><a href="/Blog/BlogDetay/@x.ID">@x.Baslik</a></li>
        }

    </ul>
    <a href="/Blog/Index/" class="link1">Tüm Blokları Gör</a>
</div>

TatilSeyahatSitesi/Views/Anasayfa/Partial4.cshtml
@using TatilSeyahatSitesi.Models.Siniflar
@model List<Blog>

<div class="padding1">
    <h4>En Beğendiğim Yerler</h4>
    <div class="box-left">
        @foreach (var x in Model)
        {
            <div class="bot-img">
                <img src="@x.BlogImage" style="width:120px; height:65px;" alt="" />
            </div>
            <div class="bot-desc">
                <p>@x.Aciklama.Substring(0, 80)...</p>
            </div>
            <div class="clear"></div>

        }
    </div>

    @Html.Action("Partial5", "Anasayfa")

</div>

TatilSeyahatSitesi/Views/Anasayfa/Partial5.cshtml
@using TatilSeyahatSitesi.Models.Siniflar
@model List<Blog>


<div class="box1-left">
    @foreach (var x in Model)
    {
        <div class="bot-img">
            <img src="@x.BlogImage" style="width:120px; height:65px;" alt="" />
        </div>
        <div class="bot-desc1">
            <p>@x.Aciklama.Substring(0, 80)...</p>
        </div>
        <div class="clear"></div>
    }
</div>